### ISSUE TITLE
fsad

### ISSUE THREAD

**Issue by tsubasa-sris** [Fendo181/osan_dev#1]
### 困っていること

(自分・チーム・サービス・ユーザーが直面している課題を書きます。)

### ゴール

(課題に対して、理想ではどうなっているべきか、どうあって欲しいかを書きます。このゴールが達成された時に issue を close します)

### 相談したいこと

(ゴールにいたるために、悩んでいること、決めて欲しいこと、助言してもらいたいことを書きます。)

### 関係者

(相談したい人にメンションします。)

**Comment by Fendo181** [comment]
hogehoge
